fix some typos, link layout, and translations in Japanese `Install` page.
numpy/numpy.org pull request #424
Opened 2021-04-24 12:32 UTC by AtsushiSakai

#### Brief description of what is fixed or changed

I fixed some typos, link layout, and translations in Japanese `Install` page to fix #423

2021-04-24 13:45 UTC, AtsushiSakai commented
@kngwyu I'm happy for you to review this PR and whole `Install` page if you have time.

2021-04-24 20:21 UTC, rgommers commented
I've pushed some changes to bring this branch in sync with master. It is no longer necessary to touch `config.yaml` (was a generated file, deleted now) or to comment out `disabledLanguages`. The preview builds now always show translations; the deploy builds not yet.

Locally you can set an environment variable once: `export NUMPYORG_WITH_TRANSLATIONS = "1"`, and then building the site with:
```
python gen_config.py && hugo
```
will show the translations.

2021-04-25 05:38 UTC, kngwyu requested changes
Thanks for the fix!
> whole Install page if you have time.

OK, I'm going to create a (possibly) big PR after merging this, to address some typical mistakes at once (e.g., use some regex to replace Numpy by NumPy). Please let me know if another way is better (e.g., crowdin or series of small PRs).

2021-04-25 05:38 UTC, kngwyu commented on content/ja/install.md
> +## Numpyパッケージと高速線形代数ライブラリ
```suggestion
## NumPyパッケージと高速線形代数ライブラリ
```

2021-04-25 05:38 UTC, kngwyu commented on content/ja/install.md
> +Numpy は他の Python パッケージに依存していませんが、高速な線形代数ライブラリ、一般的には[インテル® MKL](https://software.intel.com/en-us/mkl)、または [OpenBLAS](https://www.openblas.net/) に依存しています。 ユーザーはこれらの線形代数ライブラリのインストールを心配する必要はありません (Numpy
```suggestion
NumPy は他の Python パッケージに依存していませんが、高速な線形代数ライブラリに依存しています。典型的には、[インテル® MKL](https://software.intel.com/en-us/mkl)や[OpenBLAS](https://www.openblas.net/)がこれにあたります。ユーザーは、これらの線形代数ライブラリのインストールを心配する必要はありません (NumPyのインストール方法に、あらかじめ含まれているためです)。 高度なユーザーは、使用されているBLASがパフォーマンスや、動作、ディスク上のサイズに影響を与えるため、より詳細を知りたがるかもしれません。
```

2021-04-25 05:38 UTC, kngwyu commented on content/ja/install.md
> +- conda-forgeのチャンネルでは、Numpyはダミーの「BLAS」パッケージを使ってビルドされています。 ユーザーがconda-forgeからNumPyをインストールすると、BLASパッケージが実際のライブラリと一緒にインストールされます - デフォルトはOpenBLASですが、MKL(default チャンネルの場合)やBLIS、またはBLASを利用することもできます。
```suggestion
- conda-forgeのチャンネルでは、NumPyはダミーの「BLAS」パッケージを使ってビルドされています。 ユーザーがconda-forgeからNumPyをインストールすると、BLASパッケージが実際のライブラリと一緒にインストールされます - デフォルトはOpenBLASですが、MKL(default チャンネルの場合)やBLIS、またはBLASを利用することもできます。 
```

2021-04-25 05:38 UTC, kngwyu commented on content/ja/install.md
> +- MKLは通常、OpenBLASよりも少し速く、よりロバストな結果が得られます。
I guess that 'more robust' means 'numerically more stable'.
```suggestion
- MKLは通常、OpenBLASよりも少し速く、より頑健です。 
```

2021-04-25 05:38 UTC, kngwyu commented on content/ja/install.md
> +- インテル® MKL はオープンソースではありません。 通常の使用では問題ではありませんが、 ユーザーが Numpy で構築されたアプリケーションを再配布する必要がある場合、これは 問題が発生する可能性があります。
```suggestion
- インテル® MKL はオープンソースではありません。 通常の使用では問題ではありませんが、 ユーザーが NumPy で構築されたアプリケーションを再配布する必要がある場合、これは 問題が発生する可能性があります。 
```

2021-04-25 05:38 UTC, kngwyu commented on content/ja/install.md
> +- MKLとOpenBLASの両方とも、 <code>np.dot</code>のような関数呼び出しにマルチスレッドを使用し、スレッド数はビルド時オプションと環境変数の両方で決定されます。 多くの場合、すべての CPU コアが使用されます。 これによりユーザーに予期しないことが起こることがあります。例えばNumPy 自体は、関数呼び出しを自動的に並列化しないことです。 線形代数ライブラリの配列処
```suggestion
- MKLとOpenBLASの両方とも、 <code>np.dot</code>のような関数呼び出しにマルチスレッドを使用し、スレッド数はビルド時オプションと環境変数の両方で決定されます。 多くの場合、すべての CPU コアが使用されます。 これにユーザーにとっては予想外のことかもしれません。NumPy 自体は、関数呼び出しを自動的に並列化しないからです。 自動並列化により、一般にはパフォーマンスが向上しますが、逆にパフォーマンスが悪化する場合もあります。例えば、Daskやscikit-learn、multiprocessingなど別のレベルの並列化を使用している場合です。

2021-04-25 07:19 UTC, rgommers commented
> OK, I'm going to create a (possibly) big PR after merging this, to address some typical mistakes at once (e.g., use some regex to replace Numpy by NumPy). Please let me know if another way is better (e.g., crowdin or series of small PRs).

A PR sounds great, thanks @kngwyu. I think once the dust has settled, Crowdin will be nicer for small updates, but for now let's do whatever makes the most sense.

2021-04-25 12:12 UTC, AtsushiSakai commented on content/ja/install.md
> +- MKLは通常、OpenBLASよりも少し速く、よりロバストな結果が得られます。
I feel `より頑健です` is a little bit weird. How is "より安定した解を得られます"?

2021-04-25 13:48 UTC, kngwyu commented on content/ja/install.md
> +- MKLは通常、OpenBLASよりも少し速く、よりロバストな結果が得られます。
Sounds nice 👍🏼

2021-04-26 12:41 UTC, AtsushiSakai commented
I think this PR is ready to merge.

2021-04-26 16:28 UTC, rgommers approved these changes
Okay, in it goes - thanks @AtsushiSakai and @kngwyu!

2021-04-26 16:28 UTC, merged