DOC: Add how to contribute translations in crowdin
numpy/numpy.org pull request #681
Opened 2023-08-29 11:38 UTC by tkoyama010

#### Brief description of what is fixed or changed

DOC: Add how to contribute translations in crowdin

2023-08-30 02:12 UTC, steppi commented
Thanks @tkoyama010. I like the idea of giving more info on how to join the project, but to me this gives the impression that anyone can join Crowdin and start translating. What we want people to know is how to get in touch with a translation manager. After that I'll handle the process, inviting and on-boarding people. I'm going to think a bit about what info we should put here and would appreciate any input and advice you have to offer.

2023-08-30 02:47 UTC, tkoyama010 commented
Thank you for your comment. crowdin has an approval feature to join the project, how about using that? There is also a function to contact the translation manager.

2025-05-12 16:49 UTC, melissawm commented
Hi all - I'm wondering if this is now all covered by https://scientific-python-translations.github.io/translate/?

Specifically, I think we need to make sure people understand the translation project for numpy.org has been moved from https://crowdin.com/project/numpyorg to the https://scientific-python.crowdin.com instance. The original numpyorg project should also be converted to an archive or deleted to prevent people working there and not having their work synced.

I have some permissions on the crowdin project but will check with other maintainers to see what we want to do there. The only immediate thing I'll do is change the project name and description so people have the correct information.

Cheers!

2025-05-14 02:55 UTC, InessaPawson reviewed
> Hi all - I'm wondering if this is now all covered by https://scientific-python-translations.github.io/translate/?

I’d say a short blurb with a link to https://scientific-python-translations.github.io/translate/ is all we need in this section now.

2025-05-14 03:47 UTC, tkoyama010 commented on content/en/contribute.md
> +Details can be found here: https://support.crowdin.com/joining-translation-project/
```suggestion
See [How to translate content using Crowdin](https://scientific-python-translations.github.io/translate/).
```

2025-05-14 03:47 UTC, tkoyama010 commented
It is ready to go!

2025-05-17 23:33 UTC, InessaPawson requested changes
@tkoyama010 I've made additional suggestions for the section to better reflect the current progress and logistics of contributing translations to numpy.org.

2025-05-17 23:42 UTC, InessaPawson reviewed
@melissawm Would love to hear your thoughts on the proposed changes. Is this what you had in mind for this section?

2025-05-17 23:43 UTC, InessaPawson approved these changes

2025-05-19 13:49 UTC, melissawm approved these changes
Looks great to me, thank you @InessaPawson and @tkoyama010 !

2025-05-19 13:49 UTC, merged