Add link and image of NumPy comics to Contribute page
numpy/numpy.org pull request #795
Opened 2024-11-18 19:29 UTC by MarsBarLee

I've added a link and image to the 'How to Contribute to NumPy' comic in the Contribute page.

However, the image is showing up as broken like this:
<img width="511" alt="Screenshot 2024-11-18 at 2 23 50 PM" src="https://github.com/user-attachments/assets/8c89ca46-538e-4cf9-a4bf-79a4134bb847">

@Mukulikaa Could you take a look at this?

2024-11-18 19:38 UTC, MarsBarLee commented
I can also resize the image so it's smaller. The image is 780kB, I can make it smaller. The other image in the `images` folder is 150kB, so I can make the resized image around the same size.

2024-11-27 17:45 UTC, InessaPawson commented on content/en/contribute.md
> +  <img src="/images/numpy-comic.png"/>
```suggestion
  <img src="static/images/content_images/numpy-comic.png" alt="NumPy Contributor comic book cover">
```
`static/images/content_images/` is a better folder for this image.

2024-11-27 17:47 UTC, InessaPawson commented on images/numpy-comic.png
@MarsBarLee To keep things organized, please move the image to the `static/images/content_images/` folder.

2024-11-27 17:54 UTC, InessaPawson commented
> I can also resize the image so it's smaller. The image is 780kB, I can make it smaller. The other image in the `images` folder is 150kB, so I can make the resized image around the same size.

@MarsBarLee A lighter image would be better. We prefer to keep them light to reduce load times.

2024-12-02 23:03 UTC, MarsBarLee commented
@InessaPawson Thank you for the suggestions! I worked with Mukulika and we fixed the image so it would display properly and at the right size. I wasn't able to get my local development server to show the image but it shows up on Netlify.

The image size right now is hard-coded with pixels- would it be worthwhile to submit a separate PR with shortcode and flexible image size? I see on the About Us page, the sponsor images uses shortcode with `sponsor.html`.

I tried this [shortcode method on a separate branch on my fork here](https://github.com/MarsBarLee/numpy.org/pull/2/files).

2024-12-16 20:36 UTC, Mukulikaa commented
I think it would be nice if you could get the shortcode commit on this PR. If everything looks fine we can merge it and then improve things later if required.

2024-12-20 04:17 UTC, InessaPawson requested changes

2024-12-20 04:25 UTC, InessaPawson commented
@MarsBarLee Your POC with the shortcode looks good. Feel free to make changes in this PR or submit a separate one.

2025-01-28 20:14 UTC, stefanv commented
Do you prefer to only have a link to the zine? Because we could also embed the flipbook directly.

2025-01-29 05:20 UTC, rgommers commented
> Do you prefer to only have a link to the zine? Because we could also embed the flipbook directly.

Independent of the answer to this, can we please have a pdf copy either in this repo (if it's small enough, say O(1 MB) or in https://github.com/numpy/archive/? Content behind an external link can disappear at any time.

2025-02-07 01:20 UTC, InessaPawson commented
> ... can we please have a pdf copy either in this repo (if it's small enough, say O(1 MB) or in https://github.com/numpy/archive/? Content behind an external link can disappear at any time.

@rgommers The .pdf file is 2.7 MB. I've added it to [numpy/archive/](https://github.com/numpy/archive/).

2025-02-10 19:06 UTC, MarsBarLee commented
Hi all, for now I'll put the PR as is with the link and then submit the shortocde version with the image afterwards.

2025-02-10 19:12 UTC, MarsBarLee commented on content/en/contribute.md
> +### 'How to Contribute to NumPy' comic
Ok, I'll remove the header.

2025-02-10 19:17 UTC, MarsBarLee commented
@stefanv A direct embed would be nice! This is how Hyezine (the flipbook host) providss their embed option through the `iframe` tag. 
```html
<iframe allowfullscreen="allowfullscreen" scrolling="no" class="fp-iframe" style="border: 1px solid lightgray; width: 100%; height: 400px;" src="https://heyzine.com/flip-book/3e66a13901.html"></iframe>
``` 

I'm not sure if the NumPy website works nice with `iframe`, but another implementation is possible.

2025-02-10 20:43 UTC, MarsBarLee commented
#834 is the shortcode implementation of this PR, adding a link and image to the comic. The shortcode version can autoresize, whereas the image size is fixed in this PR.

If we prefer the shortcode version, we could merge that instead.

2025-03-10 20:28 UTC, InessaPawson commented
Closing this PR since a [separate PR with the shortcode](https://github.com/numpy/numpy.org/pull/834
) has been submitted and merged.

2025-03-10 20:28 UTC, closed without merging